config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :follows, only: [:create, :destroy]

  get '/dashboard' => redirect('/dashboard/home')
  get '/dashboard/home' => 'dashboard#home'
  get '/dashboard/guerillart' => 'dashboard#guerillart'
  get '/dashboard/profile' => 'dashboard#profile'
  get '/dashboard/manage' => 'dashboard#manage'

  post '/shows/starting' => 'shows#starting'
  post '/shows/start' => 'shows#start'
  post '/shows/finish' => 'shows#finish'

  get '/shows/:show_id/like' => 'likes#like_toggle'
  resources :shows

  get '/artists/search' => 'artists#search'
  get '/artists/:artist_name' => 'artists#page'
  get '/artists/:artist_name/edit' => 'artists#edit'
  put '/artists/:artist_name' => 'artists#update'
  resources :artists, only: [:index, :new, :create], param: :name   #매개변수를 기존의 artist_id에서 artist_name으로 변경

  resources :posts, only: [:create, :destroy, :update]
  resources :comments, only: [:create, :destroy]

  get '/search' => 'searching#index'
  post '/search' => 'searching#getBounds'
  post '/search/select' => 'searching#select'

  get '/login' => redirect('/')
  get '/register/new' => redirect('/')
  get '/register/edit' => redirect('/')
  get '/forgot/new' => redirect('/')

  devise_for :users, :path => '', :controllers => {:sessions => 'users/sessions', :registrations => 'users/registrations'}, :path_names => { :sign_in => 'login', :password => 'forgot', :confirmation => 'confirm', :unlock => 'unblock', :registration => 'register', :sign_up => 'new', :sign_out => 'logout'}

  match '*path' => redirect('/'), via: [:get]
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!, :only => [ :new, :create, :edit, :update ]
  # before_action :isSignin, :only => [ :new, :create, :edit, :update ]

  # def isSignIn
    # unless user_signed_in?
      # redirect_to '/'
    # end
  # end


  def index
    @user = User.paginate(:page => params[:page])
  end

  def new
    if current_user.artist_name.present?
      redirect_to '/dashboard/home'
    end
    @currentPage = '아티스트신청';
  end

  def create
    if current_user.artist_name.nil?

      current_user.artist_name = params[:name]
      current_user.genre = params[:genre]
      current_user.phone_number = params[:phone_number]
      current_user.area = params[:area]
      current_user.sns = params[:sns]
      current_user.introduction = params[:introduction]
      current_user.save
      redirect_to '/dashboard/home'
    else
      flash[:alert]= "you already have one"
      redirect_to '/dashboard/home'
    end
  end

  def edit
   a = params[:artist_name]
   if a != current_user.artist_name
      redirect_to "/artists"
   end

   @users = User.find_by(artist_name: a)
   @posts = Post.all
  end

  def update
    @users = User.find(params[:user_id])
    if @users.id != current_user.id
      redirect_to "/artists"
    end

    @users.introduction = params[:introduction]
    @users.sns = params[:sns]
    @users.image = params[:image]
    @users.avatar = params[:avatar]

    if @users.save
    redirect_to :back
    else
    redirect_to :back
    end
  end

  def page
    @users = User.find_by_artist_name(params[:artist_name])
    @one_post = Post.find_by_user_id(@users)
    @posts = Post.all
    @followers = User.all
    @follow = Follow.all
  end

  def search
    @users = User.where("artist_name LIKE ?", "%#{params[:artist_name]}%")
  end

  def show
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/edit.html.erb
<%= render :partial => "/layouts/headers/header" %>

<div class="ProfileCanopy-header u-bgUserColor">
    <div class="ProfileCanopy-headerBg">
    <% if @users.image.url.nil? %>
      <img alt="" src="https://pbs.twimg.com/profile_banners/74550725/1467017138/1500x500" height="350px" width="100%" >
    <% else %>
      <img alt="" src="<%= @users.image.url%>" height="350px" width="100%" >
    <% end %>
    </div>

  <div class="AppContainer">
    <div class="ProfileCanopy-avatar">
      <a class="ProfileAvatar-container u-block js-tooltip profile-picture" data-resolved-url-large="https://pbs.twimg.com/profile_images/747350188763668481/nZ_JFwxj.jpg" data-url="https://pbs.twimg.com/profile_images/747350188763668481/nZ_JFwxj.jpg" target="_blank"
       data-original-title="<%= @users.artist_name %>-title">
    </div>
  </div>
</div>

<div class="ui container">
  <img src="https://pbs.twimg.com/profile_images/747350188763668481/nZ_JFwxj.jpg"
  alt="<%= @users.artist_name %>" class="img-circle"
  width="300" height="300">
  <!-- TODO : 부트스르탭 버리고
    시멘틱유아이로 넘어왔는데 부트스트랩 class를 쓴 흔적이 존재한다
    시멘틱유아이로 바꿔주자
  -->
  <%= form_tag "update", method: :put, multipart: true  do %>
   <div class="thumbnail">
    <div class="caption">
      <div class="form-group">
        <label for="exampleInputEmail1">자기소개</label>
        <textarea class="form-control" rows="5" name="introduction"placeholder="할말">
          <%= @users.introduction %>
        </textarea>
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">SNS</label>
        <input type="text" name="sns" value="<%= @users.sns %>"class="form-control"
         id="artistgenre" placeholder="페이스북주소?">
      </div>
      <div class="input-field">
        <%= file_field_tag :image %>
      </div>
      <div class="form-group">
        <input type="submit" class="btn btn-primary" value="추가하기">
        <input type="hidden" name="user_id" value="<%= @users.id %>">
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/artists/index.html.erb
<div class="artist-body">
  <%= render :partial => "/layouts/headers/header"%>
  <%= render :partial => "/layouts/headers/sub_artists" %>

  <div class="ui artist container">
    <div class="ui special cards" id="artist-cards">
      <div class="ui artist cards">
       <% @user.each do |user| %>
        <% if user.artist_name %>
          <div class="card">
            <% if user.avatar.url %>
            <div class="blurring dimmable image">
              <div class="ui dimmer">
                <div class="content">
                  <div class="center">
                    <div class="ui inverted button">팔로잉</div>
                  </div>
                </div>
              </div>
              <img src="<%=user.avatar.url%>">
            </div>
            <% else %>
              <div class="blurring dimmable image">
                <div class="ui dimmer">
                  <div class="content">
                    <div class="center">
                    <% if user_signed_in? && current_user.id != user.id %>
                      <% if current_user.followings.include?(user) %>
                        <%= form_tag follow_path(user.id), method: :delete, class: "right" do %>
                          <button class="ui inverted button">팔로우 취소</button>
                        <% end %>
                      <% else %>
                        <%= form_tag follows_path, class: "right" do %>
                          <input type="hidden" name="followed_id" value="<%= user.id %>" />
                          <button class="ui inverted button">팔로우</button>
                        <% end %>
                      <% end %>
                    <% end %>
                    </div>
                  </div>
                </div>
                <img class="ui image" src="/images/iu.jpg">
              </div>
            <% end %>
            <div class="content">
              <a class="header" href="/artists/<%=user.artist_name%>">
                <%=user.artist_name%>
              </a>
              <div class="meta">
                <a><%=user.genre%></a>
              </div>
              <div class="description">
               <%=user.introduction%>
              </div>
            </div>
          </div>
        <% end %>
       <% end %>
      </div>
    </div>
    <%= will_paginate @user %>
  </div>
</div>

app/views/artists/new.html.erb
<%= render :partial => "/layouts/headers/header" %>
<%= render :partial => "/layouts/headers/dashboard" %>

<div class="ui container">
  <h2 class="ui dividing header">아티스트 신청서</h2>
  <div class="ui four statistics">
    <div class="statistic">
      <div class="value">
        <i class="users icon"></i> <%=current_user.id%>
      </div>
      <div class="label">
        Artist
      </div>
    </div>
    <div class="statistic">
      <div class="value">
        <img src="/images/iu.jpg" class="ui circular inline image">
        <%=current_user.id%>
      </div>
      <div class="label">
        Team Members
      </div>
    </div>
  </div>

  <%= form_tag artists_path do %>
  <div class="ui form">
    <div class="required twelve field">
      <label>아티스트명</label>
      <input type="text" name="name" class="" id="artistname" placeholder="아티스트명은 변경할 수 없습니다" required>
    </div>
    <div class="field required">
      <label>장르</label>
      <select class="ui fluid dropdown" id="select_genre" name="genre">
       <option value="">장르를 선택해주세요</option>
       <option value="힙합/랩">힙합/랩</option>
       <option value="R&B소울">R&B소울</option>
       <option value="댄스">댄스</option>
       <option value="일렉트로닉">일렉트로닉</option>
       <option value="록">록</option>
       <option value="재즈">재즈</option>
       <option value="클래식">클래식</option>
       <option value="팝">팝</option>
      </select>
    </div>
    <div class="field required">
      <label>전화번호</label>
      <input type="text" name="phone_number" class="" id="artistgenre" placeholder="전화번호를 입력해주세요"required>
    </div>
    <div class="field required">
      <label>주활동지역</label>
      <input type="text" name="area" class="" id="artistgenre" placeholder="주로 플레이하는 지역이 어디인가요?" required>
    </div>
    <div class="field required">
      <label>SNS</label>
      <input type="text" name="sns" class="" id="artistgenre" placeholder="페이스북주소?">
    </div>
    <div class="field required">
      <label>자기소개</label>
      <textarea class="" rows="5" name="introduction" placeholder="할말"></textarea>
    </div>

      <div class="form-group">
        <input type="submit" class="ui grey basic button" value="추가하기">
      </div>
  </div>
  <% end %>

</div>

app/views/artists/page.html.erb
<%= render :partial => "/layouts/headers/header" %>

<div class="ProfileCanopy-header u-bgUserColor">
    <div class="ProfileCanopy-headerBg">
    <% if @users.image.url.nil? %>
      <img  src="https://www.beatlesbible.com/wp/media/1400x400-history_01.jpg" height="350px" width="100%" >
    <% else %>
      <img  src="<%= @users.image.url%>" height="350px" width="100%" >
    <% end %>
    </div>
</div>

<div class="ui tabular menu">
  <div class="active item" data-tab="post">포스트</div>
  <div class="item" data-tab="following">팔로잉</div>
  <div class="item" data-tab="follower">팔로워</div>
  <div class="item" data-tab="show">공연들</div>
</div>




<div class="active ui tab" data-tab="post"> <!-- post tab이고 default tab -->
<!-- 아티스트 프로필, 왼쪽에 위치한다-->
  <div class="profile ui container fluid">  <!-- profile contianer fluid 시작  -->
    <div class="ui left aligned card">
      <div class="content">
        <div class="header">
        <i class="users icon"></i>
          <%= @users.artist_name %>
        </div>
      </div>
      <div class="content">
        <div class="ui small feed">
          <div class="event">
            <div class="content">
              <div class="summary">
                <i class="linkify icon"></i>
                <%= @users.sns %></br>
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              <div class="summary">
              <i class="tags icon"></i>
                <%= @users.genre %></br>
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              <div class="summary">
               <i class="marker icon"></i>
               <%= @users.area %>
              </div>
            </div>
          </div>
          <div class="event">
            <div class="content">
              <div class="summary">
              <i class="comments icon"></i>
                <%= @users.introduction %></br>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="extra content">
        <% if user_signed_in? && current_user.id != @users.id %>
          <% if current_user.followings.include?(@users) %>
            <%= form_tag follow_path(@users.id), method: :delete, class: "right" do %>
              <button class="btn btn-primary">팔로우 취소</button>
            <% end %>
          <% else %>
            <%= form_tag follows_path, class: "right" do %>
              <input type="hidden" name="followed_id" value="<%= @users.id %>" />
              <button class="btn btn-primary">팔로우</button>
            <% end %>
          <% end %>
        <% end %>
        </span>
        <% unless current_user.nil? %>
          <% if current_user.artist_name == @users.artist_name %>
            <% user = @users.artist_name %>
            <%= link_to "수정하기", controller: "artists", action:"edit", artist_name: user %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>


  <div class="post-by">
    <!-- 새 글 작성 폼시작 -->
    <% unless current_user.nil? %>
      <% if @users.artist_name == current_user.artist_name %>
        <%= form_tag posts_path do %>
          <div class="panel panel-default">
            <div class="panel-body">
              <textarea class="form-control counted" value="content" name="content" placeholder="무슨 생각을 하고 있어요?" rows="5"></textarea>
              <h6 class="pull-right" id="counter">320 characters remaining</h6>
              <button class="btn btn-info" type="submit">글쓰기</button>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <!-- 글 보여주기 -->
    <% @posts.reverse.each do |post| %>
      <% if @users.id == post.user_id %><!-- 현 아티스트페이지의 아티스트가 쓴 글만 보인다 -->
      <div class="posts_get thumbnail">
        <!-- 아티스트가 글쓴 내용 -->
        <div class="ui comments">
          <div class="comment">
            <a class="avatar">
              <img src="http://semantic-ui.com/images/avatar/small/elliot.jpg">
            </a>
            <div class="content">
              <a class="author"><%=@users.name%></a>
              <div class="metadata"><%= post.created_at%></div>
              <div class="text">
                <p><%= post.content %></p>
              </div>
            </div>
          </div>
         </div>
        <div>
          <a class="comment-style"id="op-comments-<%= post.id %>">댓글
            <b><%= post.comments.size %></b>
          </a>
        </div>
        <hr>
        <input type="hidden" value="<%= post.id %>" name="<%= post.id %>">
        <div class="ui fluid input">
          <input class="item" name="content" rows="2" id="content_<%= post.id %>" placeholder="댓글 내용을 입력하세요">
        </div>
        <button value="<%= post.id %>" type="submit" class="ui fluid button reply_submit">작성하기</button>
        <!-- 글쓴 내용에 달린 댓글 출력 -->
        <% unless post.comments.nil? %>
          <% post.comments.each do |comment| %>
          <div class="ui comments">
            <div class="comment">
              <a class="avatar">
                <img src="http://semantic-ui.com/images/avatar/small/elliot.jpg">
              </a>
              <div class="content">
                <a class="author"><%= comment.user.name %></a>
                <div class="metadata">
                 <%= comment.created_at.in_time_zone("Asia/Seoul").strftime("%Y-%m-%d %H:%M:%S") %>
                </div>
                <div class="text">
                  <p><%= comment.content %></p>
                </div>
              </div>
            </div>
           </div>
          <div id="reply_<%= post.id %>"></div>
          <% end %>
        <% end %><!-- 끝 : 글쓴 내용에 달린 댓글 출력 -->
      </div>
     <% end %><!-- 끝 : 현 아티스트페이지의 아티스트가 쓴 글만 보인다 -->
   <% end %><!-- 끝 : 글 보여주기 -->
  </div><!--  Content !-->
</div>


     <!-- 가수의 팔로잉  시작 -->
     <div class="ui tab" data-tab="following">
      <div class="ui grid container ">
       <% @follow.each do |f| %>
         <% if f.follower_id == @users.id %>
         <% my_star = User.find_by(id: f.followed_id) %>
          <div class="four wide column">
            <div class="ui cards">
              <div class="card">
                <div class="content">
                  <img class="right floated mini ui image" src="http://semantic-ui.com/images/avatar/large/elliot.jpg">
                  <div class="header"><%= my_star.artist_name %></div>
                  <div class="meta"><%= my_star.genre%></div>
                  <div class="description"><%= my_star.introduction%></div>
                </div>
                <div class="extra content">
                  <div class="ui two buttons">
                    <div class="ui basic green button">메세지</div>
                    <div class="ui basic red button">차단</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
       <% end %>
     </div>
    </div>
    <!-- 가수의 팔로잉 종료 !-->


   <!-- 팔로워들 정보 보여주기 시작-->
   <div class="ui tab" data-tab="follower">
    <div class="ui grid container ">
     <% @follow.each do |f| %>
       <% if f.followed_id == @users.id %>
         <% fan = User.find_by(id: f.follower_id) %>
          <div class="four wide column">
            <div class="ui cards">
              <div class="card">
                <div class="content">
                  <img class="right floated mini ui image" src="http://semantic-ui.com/images/avatar/large/elliot.jpg">
                  <div class="header"><%= fan.name %></div>
                  <div class="meta"><%= fan.email%></div>
                  <div class="description">since:<%= fan.created_at%></div>
                </div>
                <div class="extra content">
                  <div class="ui two buttons">
                    <div class="ui basic green button">메세지</div>
                    <div class="ui basic red button">차단</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
         <% end %>
       <% end %>
     </div>
   </div>
   <!-- 팔로워들 정보보여주기 종료 -->


   <!-- 추후에 기능 개발
  <div class="ui tab" data-tab="collabo">
    <h1> 커밍순~!!! </h1>
     콜라보는 공연정보가 와야한다Tab Content
  </div>
  !-->

  <div class="ui tab" data-tab="show">
    <div class="ui artists-show special cards">
      <% unless @users.creations.nil?  %>
      <% @users.creations.each do |show| %>
      <div class="card">
        <div class="blurring dimmable image">
          <div class="ui inverted dimmer">
            <div class="content">
              <div class="center">
                <%= link_to "더보기", {controller: "shows", action: "show", id: show.id}, class: "ui primary button", target: "_blank" %>
              </div>
            </div>
          </div>
          <img class="ui fluid image" src="/images/portfolio/<%= (1..12).to_a.sample %>.jpg" />
        </div>
        <div class="content">
          <a class="header"><%= show.title %></a>
          <div class="meta">
            <% if show.creator.nil? %>
            <span class="date">장범준</span>
            <% else %>
            <span class="date"><%= show.creator.artist_name %></span>
            <% end %>
          </div>
          <div class="description"><%= show.location %></div>
        </div>
        <div class="extra content">
          <i class="heart icon"></i>
          <%= show.likes.size %>
          <span class="right floated"><%= show.date %></span>
        </div>
      </div>
      <% end %>
    <% end %>
    </div>
  </div>

app/views/artists/search.html.erb
<%= render :partial => "/layouts/headers/header"%>

    <div class="ui view container">
      <div class="ui special cards" id="show-genres">
        <div class="ui cards">

         <% @users.each do |user| %>
          <% if user.artist_name %>
          <% artist_name = user.artist_name %>
            <div class="card">
              <% if user.avatar.url %>
                <div class="blurring dimmable image">
                  <div class="ui dimmer">
                    <div class="content">
                      <div class="center">
                        <div class="ui inverted button">팔로잉</div>
                      </div>
                    </div>
                  </div>
                  <img src="<%=user.avatar.url%>">
                </div>
              <% else %>
                <div class="blurring dimmable image">
                  <div class="ui dimmer">
                    <div class="content">
                      <div class="center">

                      </div>
                    </div>
                  </div>
                  <img src="http://www.baedalnet.com/data/mw.cheditor/1402/c737496a1e90569ea8e24a8058a1b624_dSkWVsZntgKDtzpQEAG.jpg">
                </div>
              <% end %>

              <div class="content">
                <a class="header" href="/artists/<%=user.artist_name%>"><%=user.artist_name%><input type="hidden" name="artist_name" value="<%=user.artist_name%>"></a>
                <div class="meta">
                  <%=user.genre%>
                </div>
                <div class="description">
                 <%=user.introduction%>
                </div>
              </div>
            </div>
          <% end %>
         <% end %>

        </div>
      </div>
    </div>

app/views/artists/show.html.erb
<%= render :partial => "/layouts/headers/header"%>

    <div class="ui view container">
      <div class="ui special cards" id="show-genres">
        <div class="ui cards">

          <% if @user.artist_name %>
          <% artist_name = @user.artist_name %>
            <div class="card">
              <% if @user.avatar.url %>
                <div class="blurring dimmable image">
                  <div class="ui dimmer">
                    <div class="content">
                      <div class="center">
                        <div class="ui inverted button">팔로잉</div>
                      </div>
                    </div>
                  </div>
                  <img src="<%=@user.avatar.url%>">
                </div>
              <% else %>
                <div class="blurring dimmable image">
                  <div class="ui dimmer">
                    <div class="content">
                      <div class="center">

                      </div>
                    </div>
                  </div>
                  <img src="http://www.baedalnet.com/data/mw.cheditor/1402/c737496a1e90569ea8e24a8058a1b624_dSkWVsZntgKDtzpQEAG.jpg">
                </div>
              <% end %>

              <div class="content">
                <a class="header" href="/artists/name/<%=@user.artist_name%>"><%=@user.artist_name%><input type="hidden" name="artist_name" value="<%=@user.artist_name%>"></a>
                <div class="meta">
                  <%=@user.genre%>
                </div>
                <div class="description">
                 <%=@user.introduction%>
                </div>
              </div>
            </div>
          <% end %>

        </div>
      </div>
    </div>