config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :follows, only: [:create, :destroy]

  get '/dashboard' => redirect('/dashboard/home')
  get '/dashboard/home' => 'dashboard#home'
  get '/dashboard/guerillart' => 'dashboard#guerillart'
  get '/dashboard/profile' => 'dashboard#profile'
  get '/dashboard/manage' => 'dashboard#manage'

  post '/shows/starting' => 'shows#starting'
  post '/shows/start' => 'shows#start'
  post '/shows/finish' => 'shows#finish'

  get '/shows/:show_id/like' => 'likes#like_toggle'
  resources :shows

  get '/artists/search' => 'artists#search'
  get '/artists/:artist_name' => 'artists#page'
  get '/artists/:artist_name/edit' => 'artists#edit'
  put '/artists/:artist_name' => 'artists#update'
  resources :artists, only: [:index, :new, :create], param: :name   #매개변수를 기존의 artist_id에서 artist_name으로 변경

  resources :posts, only: [:create, :destroy, :update]
  resources :comments, only: [:create, :destroy]

  get '/search' => 'searching#index'
  post '/search' => 'searching#getBounds'
  post '/search/select' => 'searching#select'

  get '/login' => redirect('/')
  get '/register/new' => redirect('/')
  get '/register/edit' => redirect('/')
  get '/forgot/new' => redirect('/')

  devise_for :users, :path => '', :controllers => {:sessions => 'users/sessions', :registrations => 'users/registrations'}, :path_names => { :sign_in => 'login', :password => 'forgot', :confirmation => 'confirm', :unlock => 'unblock', :registration => 'register', :sign_up => 'new', :sign_out => 'logout'}

  match '*path' => redirect('/'), via: [:get]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :show
  belongs_to :post
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  # 팔로우 신청한 유저
  # 관계 이름 : follower
  # 모델 명 : User
  belongs_to :follower, class_name: "User"

  # 팔로우 신청 받은 유저
  # 관계 이름 : followed
  # 모델 명 : User
  belongs_to :followed, class_name: "User"

end

app/models/like.rb
class Like < ActiveRecord::Base
      belongs_to :user
      belongs_to :show
end

app/models/like_show.rb
class LikeShow < ActiveRecord::Base
  belongs_to :user
  belongs_to :show
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/show.rb
class Show < ActiveRecord::Base
  searchable do
    float :location_x
    float :location_y
    integer :status
    integer :creator_id
  end
  
  belongs_to :creator, :class_name => User  #공연 등록자에 종속
  
  has_many :like_shows
  has_many :users, through: :like_shows
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :comments

  #지도 검색 거리순 정렬에 사용
  attr_accessor :dist 

  def cnt_view(show)
    if show.view_count.nil?
      show.view_count = 0
    else
    	show.update_attribute "view_count", show.view_count = show.view_count + 1
      show.save
    end
  end
  # 한 페이지당 보이는 카드 수
  self.per_page = 9 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, length: { in: 2..12 }
  validates :phone_number, 
            :numericality => {:only_integer => true },
            :allow_nil => true
        
  

  mount_uploader :avatar, AvatarUploader
  mount_uploader :image, BannerImageUploader


  has_many :registers
  has_many :like_shows
  has_many :shows, through: :like_shows
  has_many :posts
  has_many :comments
  has_many :likes

  has_many :liked_shows, through: :likes, source: :show

  # 관계 이름 : follower_relations(다른 이름으로 변경 가능)
  # 외래키 : followed_id
  # 모델명 : Follow
  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  # 관계 이름 : followers (다른 이름으로 변경 가능)
  # follow_relations를 통해 가져올 값 : follower ( follow.follower )
  has_many :followers, through: :follower_relations, source: :follower
  has_many :following_relations, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relations, source: :followed


  has_many :creations, :class_name => Show , :foreign_key => :creator_id  #아티스트는 여러 개의 공연을 등록할 수 있다.



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def is_like?(show)
    Like.find_by(user_id: self.id, show_id: show.id).present?
  end
  # 한 페이지당 보여지는 카드 수
  self.per_page = 9
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # unless user_signed_in?
      # redirect_to '/users/sign_in'
    # end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def like_toggle
    like = Like.find_by(user_id: current_user.id,
                        show_id: params[:show_id])

    if like.nil?
      Like.create(user_id: current_user.id,
                  show_id: params[:show_id])
    else
      like.destroy
    end

    redirect_to :back
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    @post = Post.new
    @post.content = params[:content]
    @post.user_id = current_user.id

    if  @post.save
    redirect_to :back
    else
    redirect_to :back
    end
  end

  def update 
    @post = Post.find(params[:id])
  end
  
  def edit
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def resource_name
  :user
end

def resource
  @resource ||= User.new
end

def devise_mapping
 @devise_mapping ||= Devise.mappings[:user]
end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searching_helper.rb
module SearchingHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/layouts/_changeGenre.html.erb
<div id="#<%= @current_genre %>"  class="clearfix grid" style="margin-top:170px">
    <%
      @cnt = 1
      @shows.reverse.each do |show|
      if show.genre == @current_genre || "모아보기" == @current_genre
    %>
    <figure class="effect-oscar wowload fadeInUp">
      <img src="images/portfolio/<%= @cnt %>.jpg" alt="img01"/>
      <figcaption>
        <h2><%= show.title %></h2>
        <p><%= show.location %><br>
            <%= show.date  %><br>
            <%= show.time %><br>
        </p>
        <p>
          <a class="btn" data-toggle="modal" data-target="#upcomings-modal">More</a>
        </p>
      </figcaption>
    </figure>
    <%
      @cnt += 1
    end
  end
%>
</div>

app/views/layouts/_guerillart_followed_artist.html.erb
<style>
.ui.guerillart.tab {
  display: inherit;
  margin-top: 40px;
}
.ui.guerillart.cards {
  float: left;
  margin-right: 10px;
  margin-bottom: 10px;
}
</style>
<div class="ui guerillart tab">
  <% @followed.each do |f| %>
  <%# @followed는 현재 유저 아이디가 퐐로워 아이디로 등록한, 모든 퐐로잉을 가져옴%>
    <% @artists_you_following = User.where(id: f.followed.id) %>
      <% @artists_you_following.each do |a| %>
           <div class="four wide column">
             <div class="ui guerillart cards">
               <div class="card">
                 <div class="content">
                   <img class="right floated mini ui image" src="http://semantic-ui.com/images/avatar/large/elliot.jpg">
                   <div class="header"><%= a.artist_name %></div>
                   <div class="meta"><%= a.email %></div>
                   <div class="description">since:<%= a.created_at %></div>
                 </div>
                 <div class="extra content">
                   <div class="ui two buttons">
                     <div class="ui basic green button">메세지</div>
                     <div class="ui basic red button">차단</div>
                   </div>
                 </div>
               </div>
             </div>
           </div>
      <% end %>
    <% end %>
</div>

app/views/layouts/_header_dashboard.html.erb
<style>
.ui.subshow.menu {
  margin-top: -15px;
  background: #FAFAFA;
  border-radius: 0;
  border:none;
}
/* dropdown */
.ui.button {
  background: transparent;
}
.ui.sub.dropdown>.text {
  font-weight: bold;
  color: rgba(0, 0, 0, 0.8);
}
div.ui.button.sub.dropdown {
  text-align: center;
}
/* 전체 가운데 정렬 */
.ui.button.sub.dropdown.genre, .ui.button.sub.dropdown.show {
  margin : 0 auto;
}
.ui.subshow.container {
  width: 300px;
}
</style>
<div class="ui subshow menu">
  <div class="ui subshow container">
     <a class="header item" href="/dashboard/home" method="get">대쉬보드</a>
     <a class="header item" href="/dashboard/guerillart" method="get">나의게릴라트</a>
     <a class="header item" href="/dashboard/profile" method="get">계정관리</a>
    <% if current_user.artist_name %>
      <% artist_name = current_user.artist_name %>
        <a class="header item" href="/shows/new" method="get">공연등록</a>
    <% else %>
        <a class="header item" href="/artists/new" method="get">아티스트 신청서</a>
    <% end %>
  </div>
</div>

<script>
$('.show.dropdown')
  .dropdown();
;
$('.genre.dropdown')
  .dropdown();
;
</script>

app/views/layouts/_sub_header_artists.html.erb
<style>
.ui.subshow.menu {
  margin-top: -15px;
  background: #FAFAFA;
  border-radius: 0;
  border:none;
}
/* dropdown */
.ui.button {
  background: transparent;
}
.ui.sub.dropdown>.text {
  font-weight: bold;
  color: rgba(0, 0, 0, 0.8);
}
div.ui.button.sub.dropdown {
  text-align: center;
}
/* 전체 가운데 정렬 */
.ui.button.sub.dropdown.genre, .ui.button.sub.dropdown.show {
  margin : 0 auto;
}
.ui.subshow.container {
  width: 300px;
}
</style>
<div class="ui subshow menu">
  <div class="ui subshow container">

    <div class="ui button sub genre dropdown genre">
      <div class="text">
   <%= link_to "인기순", controller: "artists", action:"index", who_is: "인기순"  %>
      </div>
      <div class="ui simple dropdown menu">
      </div>
    </div>
    <!-- 공연 -->
    <div class="ui button sub show dropdown show">
      <div class="text">
       <%= link_to "나의아티스트", controller: "artists", action:"index", who_is: "나의아티스트"  %>
      </div>
    </div>


  </div>
</div>
<script>
$('.show.dropdown')
  .dropdown();
;
$('.genre.dropdown')
  .dropdown();
;
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Guerillart</title>
		<%= stylesheet_link_tag    'application', media: 'all'%>
		<%= javascript_include_tag 'application' %>

		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<link rel="stylesheet" type="text/css" href="/semantic/dist/semantic.min.css">
		<script src="/semantic/dist/semantic.min.js"></script>
		<%= csrf_meta_tags %>
		<%= favicon_link_tag 'favicon.ico' %>
		<meta charset="UTF-8" />
	</head>

	<body>
		<%= yield %>
	</body>
	<!-- <%= render "/layouts/footers/footer" %> -->

</html>

app/views/layouts/footers/_footer.html.erb
<footer id="footer">
  <div class="ui horizontal list">
    <div class="item 1">
      About Us
    </div>
    <div class="item 2">
      Copyright © 2016 Guerillart. All rights reserved.
    </div>
    <div class="item 3">
      Guerillart?
    </div>
  </div>
</footer>

app/views/layouts/guerillarts/_followed_artist.html.erb
<style>
.ui.guerillart.tab {
  display: inherit;
  margin-top: 40px;
}
.ui.guerillart.cards {
  float: left;
  margin-right: 10px;
  margin-bottom: 10px;
}
</style>
<div class="ui guerillart tab">
  <% @followed.each do |f| %>
  <%# @followed는 현재 유저 아이디가 퐐로워 아이디로 등록한, 모든 퐐로잉을 가져옴%>
    <% @artists_you_following = User.where(id: f.followed.id) %>
      <% @artists_you_following.each do |a| %>
           <div class="four wide column">
             <div class="ui guerillart cards">
               <div class="card">
                 <div class="content">
                   <img class="right floated mini ui image" src="http://semantic-ui.com/images/avatar/large/elliot.jpg">
                   <div class="header"><%= a.artist_name %></div>
                   <div class="meta"><%= a.email %></div>
                   <div class="description">since:<%= a.created_at %></div>
                 </div>
                 <div class="extra content">
                   <div class="ui two buttons">
                     <div class="ui basic green button">메세지</div>
                     <div class="ui basic red button">차단</div>
                   </div>
                 </div>
               </div>
             </div>
           </div>
      <% end %>
    <% end %>
</div>

app/views/layouts/guerillarts/_liked_show.html.erb
<%#나의 게릴라트 페이지의 , 찜한 공연 %>
    <div class="ui guerillart special cards" id="show-genres">
    <%
      @yourlikes.each do |liked_show|
        @shows.reverse.each do |show|
          if liked_show.show_id == show.id
    %>
      <div class="card">
        <div class="blurring dimmable image">
          <div class="ui inverted dimmer">
            <div class="content">
              <div class="center">
                <%= link_to "더보기", {controller: "shows", action: "show", id: show.id}, class: "ui primary button", target: "_blank" %>
              </div>
            </div>
          </div>
          <img class="ui fluid image" src="/images/portfolio/<%= (1..12).to_a.sample %>.jpg" />
        </div>
        <div class="content">
          <a class="header"><%= show.title %></a>
          <div class="meta">
            <% if show.creator.nil? %>
            <span class="date">장범준</span>
            <% else %>
            <span class="date"><%= show.creator.artist_name %></span>
            <% end %>
          </div>
          <div class="description">
            <%= show.location %>
          </div>
        </div>
        <div class="extra content">
            <i class="heart icon"></i>
            <%= show.likes.size %>
            <span class="right floated"><%= show.date %></span>
          </div>
        </div><!-- card -->
      <% end %>
    <% end %>
  <% end %>
  </div>

app/views/layouts/headers/_header.html.erb
<%# 메인홈말고 모든 페이지에서 쓰이는 헤더 %>

<!-- Side navbar menu -->
<div class="ui container">
  <div class="ui sidebar inverted vertical menu">
    <%= link_to "공연", shows_path, class: "ui item" %>
    <%= link_to "아티스트", artists_path, class: "ui item" %>
    <% if user_signed_in? %>
      <%= link_to "대쉬보드", dashboard_home_path, class: "item" %>
      <%= link_to "나의게릴라트", dashboard_guerillart_path, class: "item" %>
      <%= link_to "계정관리", dashboard_profile_path, class: "item" %>
      <% if current_user.artist_name? %>
      <%= link_to "공연관리", dashboard_manage_path, class: "item" %>
<%
=begin
%>
      <a class="item" href="/artists/<%=current_user.artist_name%>">
        <%=current_user.artist_name%>페이지
      </a>
<%
=end
%>
      <% end %>
      <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "item" %>
    <% else %>
       <a class="ui item start_signup_modal">회원가입</a>
       <a class="ui item start_signin_modal">로그인</a>
    <% end %>
  </div>

<!-- Site contents-->
  <div class="pusher">
      <div class="ui secondary menu general-header" id="general-header">
        <a class="item sidebar-icon" id="sidebar-icon-2"><i class="content icon"></i></a>
        <a class="ui item" href="/">GUERILLART</a>
        <!-- 검색시작 -->
        <% if controller.controller_name + controller.action_name == "artistsindex" || controller.controller_name + controller.action_name == "showsindex" %>
          <% if controller.controller_name == "artists" %>
            <% redirect = "artists/search"
               params = "artist_name"
               current_word = "아티스트"
            %>
          <% else %>
            <% redirect = "search"
               params = "location"
               current_word = "위치"
            %>
          <% end %>
          <div class="item">
            <div class="ui transparent icon input">
              <form action="/<%=redirect-%>" method="get">
              <input type="text" name="<%=params%>" placeholder="<%=current_word%>를 검색해보세요.">
              <i class="search link icon"></i>
              </form>
            </div>
          </div>
        <% end %>
        <!-- 검색종료 -->

        <div class="right menu"> <!-- 오른쪽 Navbar -->
          <!--공연등록 시작-->
          <% if controller.action_name == "index" && controller.controller_name == "home" %>
            <!--공연 control-->
            <% if user_signed_in? and current_user.artist_name.present? %>

              <!-- 현재 공연중이라면 -->
              <% if current_user.playing_id != 0 %>
                <%= render :partial => "/shows/finish" %>
                <a class="ui item" style="color: red;" id="start_showFinish_modal">종료하기</a>

                <script>
                  document.getElementById('start_showFinish_modal').onclick = function() {
                    $('.ui.basic.modal.nav#showFinish').modal('show');
                  }
                </script>
              <!-- 공연중이 아니라면 -->
              <% else %>
                <%= render :partial => "/shows/start" %>

                <script>
                console.log('<%=current_user.playing_id%>');
                </script>

                <div class="ui right dropdown item">
                  <div class="ui simple dropdown">
                    <div class="text" style="color: yellow;">시작하기</div>
                    <i class="dropdown icon" style="color: yellow;"></i>
                      <div class="menu">
                        <div class="item st" value="0">즉석 공연</div>
                        <div class="divider"></div>
                        <!-- 예정 공연 검색 -->
                        <% Show.index %>
                        <% @res_search = Show.search do %>
                          <% all_of do %>
                            <% with(:creator_id, current_user.id) %>
                            <% with(:status, 0) %>
                          <% end %>
                        <% end %>

                        <!-- 시간순 정렬-->
                        <% @res_search.results.sort! { |a, b| a.start <=> b.start }.each do |show| %>
                          <% if (show.start - 1.hour <= Time.now) and (Time.now <= show.start + 30.minute) %>
                              <div class="item st" value='<%= show.id %>'><%= show.start.strftime("%Y.%m.%d %H:%M") %> 공연 </div>
                          <% else %>
                              <div class="disabled item st" value='<%= show.id %>'><%= show.start.strftime("%Y.%m.%d %H:%M") %> 공연 </div>
                          <% end %>
                        <% end %>

                      </div>
                  </div>
                <script>
                // $('.ui.simple.dropdown')
                //   .dropdown('bind mouse events'){
                //     console.log("hover");
                //   }

                  // .dropdown({
                  //   action: function(text, value) {
                  //     console.log("hover");
                  //   }
                  // })
                // ;
                </script>

                </div>

                <!--각 공연 버튼 클릭 리스너 -->
                <script>
                  $('.item.st').click(function(){
                    var show_id = $(this).attr('value');
                    console.log("item st : " + show_id);
                    $.ajax({
                      type: "POST",
                      url: "/shows/starting",
                      data: { show_id: show_id},
                      success: function(result){
                        $('.ui.basic.modal.nav#showStart').modal('show');
                        var pos_input = $('input[name=pos-input]');
                        pos_input.focus();
                        pos_input.val('');
                        if(show_id != 0)  //예정 공연의 미리 입력된 장소
                          pos_input.val(result.location);
                        initMap(show_id);
                      }
                    });
                  });

                </script>

              <% end %> <!-- 공연진행 여부 End -->
            <% end %> <!-- 공연 controll End-->
          <% end %>

          <!-- 공연등록 끝 -->
           <%= link_to "공연", shows_path, class: "ui item" %>
           <%= link_to "아티스트", artists_path, class: "ui item" %>
           <%if user_signed_in?%>
             <div class="ui right dropdown item">
              <div class="ui simple dropdown">
                <div class="text"><%= current_user.name%>님 </div>
                <i class="dropdown icon"></i>
                <div class="menu">
                  <%= link_to "대쉬보드", dashboard_home_path, class: "ui item" %>
                  <%= link_to "나의게릴라트", dashboard_guerillart_path, class: "ui item" %>
                  <%= link_to "계정관리", dashboard_profile_path, class: "ui item" %>
                  <% if current_user.artist_name? %>
                    <%= link_to "공연관리", dashboard_manage_path, class: "ui item" %>
<%
=begin
%>
                    <a class="ui item" href="/artists/<%=current_user.artist_name%>">
                      <%=current_user.artist_name%>페이지
                    </a>
<%
=end
%>
                  <% end %>
                  <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "ui item" %>
                </div>
              </div>
             </div>
           <% else%>

           <a class="ui item start_signup_modal">회원가입</a>
           <a class="ui item start_signin_modal">로그인</a>
           <% end %>
        </div>
      </div>
    </div>

</div>
<%# 로그인, 회원가입, 비번찾기 모달 %>
<%= render :partial => "/devise/sessions/new" %>
<%= render :partial => "/devise/registrations/new" %>
<%= render :partial => "/devise/passwords/new" %>

app/views/layouts/headers/_home.html.erb
<%# 메인홈만 쓰이는 헤더 %>

<!-- Side navbar menu -->
<div class="ui container">
  <div class="ui sidebar inverted vertical menu">
    <%= link_to "공연", shows_path, class: "ui item" %>
    <%= link_to "아티스트", artists_path, class: "ui item" %>
    <% if user_signed_in? %>
      <%= link_to "대쉬보드", dashboard_home_path, class: "item" %>
      <%= link_to "나의게릴라트", dashboard_guerillart_path, class: "item" %>
      <%= link_to "계정관리", dashboard_profile_path, class: "item" %>
      <% if current_user.artist_name? %>
        <%= link_to "공연관리", dashboard_manage_path, class: "item" %>


        <a class="item" href="/artists/<%=current_user.artist_name%>">
          <%=current_user.artist_name%>페이지
        </a>
      <% end %>
      <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "item" %>
      <% else %>
       <a class="ui item start_signup_modal">회원가입</a>
       <a class="ui item start_signin_modal">로그인</a>
    <% end %>
  </div>

<!-- Navbar menu -->
<div class="pusher">
<header class="ui container">
  <div class="ui secondary menu home" id="home-header">
  <a class="item sidebar-icon" id="sidebar-icon-1"><i class="content icon"></i></a>
    <a class="ui item" href="/">GUERILLART</a>
    <div class="right menu"> <!-- 오른쪽 Navbar -->
      <!--공연 control-->
      <% if user_signed_in? and current_user.artist_name.present? %>

        <!-- 현재 공연중이라면 -->
        <% if current_user.playing_id != 0 %>
          <%= render :partial => "/shows/finish" %>
          <a class="ui item" style="color: red;" id="start_showFinish_modal">종료하기</a>

          <script>
            document.getElementById('start_showFinish_modal').onclick = function() {
              $('.ui.basic.modal.nav#showFinish').modal('show');
            }
          </script>
        <!-- 공연중이 아니라면 -->
        <% else %>
          <%= render :partial => "/shows/start" %>

          <script>
          console.log('<%=current_user.playing_id%>');
          </script>

          <div class="ui right dropdown item">
            <div class="ui simple dropdown">
              <div class="text" style="color: yellow;">시작하기</div>
              <i class="dropdown icon" style="color: yellow;"></i>
                <div class="menu">
                  <div class="item st" value="0">즉석 공연</div>
                  <div class="divider"></div>
                  <!-- 예정 공연 검색 -->
                  <% Show.index %>
                  <% @res_search = Show.search do %>
                    <% all_of do %>
                      <% with(:creator_id, current_user.id) %>
                      <% with(:status, 0) %>
                    <% end %>
                  <% end %>

                  <!-- 시간순 정렬-->
                  <% @res_search.results.sort! { |a, b| a.start <=> b.start }.each do |show| %>
                    <% if (show.start - 1.hour <= Time.now) and (Time.now <= show.start + 30.minute) %>
                        <div class="item st" value='<%= show.id %>'><%= show.start.strftime("%Y.%m.%d %H:%M") %> 공연 </div>
                    <% else %>
                        <div class="disabled item st" value='<%= show.id %>'><%= show.start.strftime("%Y.%m.%d %H:%M") %> 공연 </div>
                    <% end %>
                  <% end %>

                </div>
            </div>
          <script>
          // $('.ui.simple.dropdown')
          //   .dropdown('bind mouse events'){
          //     console.log("hover");
          //   }

            // .dropdown({
            //   action: function(text, value) {
            //     console.log("hover");
            //   }
            // })
          // ;
          </script>

          </div>

          <!--각 공연 버튼 클릭 리스너 -->
          <script>
            $('.item.st').click(function(){
              var show_id = $(this).attr('value');
              console.log("item st : " + show_id);
              $.ajax({
                type: "POST",
                url: "/shows/starting",
                data: { show_id: show_id},
                success: function(result){
                  $('.ui.basic.modal.nav#showStart').modal('show');
                  var pos_input = $('input[name=pos-input]');
                  pos_input.focus();
                  pos_input.val('');
                  if(show_id != 0)  //예정 공연의 미리 입력된 장소
                    pos_input.val(result.location);
                  initMap(show_id);
                }
              });
            });

          </script>

        <% end %> <!-- 공연진행 여부 End -->
      <% end %> <!-- 공연 controll End-->

      <%= link_to "공연", shows_path, class: "ui item" %>
      <%= link_to "아티스트", artists_path, class: "ui item" %>

      <!-- 로그인 상태라면 -->
      <%if user_signed_in?%>

        <div class="ui right dropdown item">
          <div class="ui simple dropdown">
            <div class="text"> <%= current_user.name%>님 </div>
            <i class="dropdown icon"></i>
            <div class="menu">
              <%= link_to "대쉬보드", dashboard_home_path, class: "ui item" %>
              <%= link_to "나의게릴라트", dashboard_guerillart_path, class: "ui item" %>
              <%= link_to "계정관리", dashboard_profile_path, class: "ui item" %>

              <% if current_user.artist_name? %>
                <%= link_to "공연관리", dashboard_manage_path, class: "ui item" %>

                <a class="ui item" href="/artists/<%=current_user.artist_name%>">
                  <%=current_user.artist_name%>페이지
                </a>

              <% end %>
              <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "ui item" %>
            </div>
          </div>
        </div>

      <!-- 로그인 상태가 아니라면 -->
      <% else%>
        <%# 로그인, 회원가입, 비번찾기 모달 %>
        <%= render :partial => "/devise/sessions/new" %>
        <%= render :partial => "/devise/registrations/new" %>
        <%= render :partial => "/devise/passwords/new" %>

        <a class="ui item start_signup_modal">회원가입</a>
        <a class="ui item start_signin_modal">로그인</a>
      <% end %>
    </div>
  </div>
</header>
<!-- </div> -->

<!-- nav modal 스타일 -->
<style>
	.ui.basic.modal.nav {
	  max-width: 450px;
    overflow: hidden;
    position: fixed;
	}
   /*nav modal x 버튼 */
  .ui.basic.modal.nav>.close {
    right: 0px;
  }
</style>